config/routes.rb
resources :projects do
  resources :vaults
end

resources :projects do
  resources :masters
end

resources :projects do
  resources :vaults do
    resources :sitems
  end
end

get 'projects/:project_id/decrypt', :to => 'masters#decrypt'
post 'projects/:project_id/decrypt', :to=> 'masters#decrypt_post'
get 'projects/:project_id/change-master', :to => 'masters#change_master'
post 'projects/:project_id/change-master', :to => 'masters#change_master_post'
get 'projects/:project_id/close-vault', :to => 'vaults#close_vault'

app/models/vault.rb
class Vault < ActiveRecord::Base
  unloadable
  acts_as_attachable :view_permission => :view_files,
                     :edit_permission => :manage_files,
                     :delete_permission => :manage_files
  belongs_to :user, :class_name => "User", :foreign_key => "user_id"
  belongs_to :project, :class_name => "Project", :foreign_key => "project_id"
  has_many :sitems, :class_name => "Sitem", :dependent => :destroy
  attr_accessible :host, :login, :password, :notes, :private
  validates_presence_of :host, :login, :password

  def private_out
    private ? 'Yes' : 'No'
  end
end

app/controllers/vault_controller.rb
class VaultController < ApplicationController
  unloadable

  before_filter :find_project, :authorize

  def index
    #check that master password exist
    @master_password = MasterPassword.find_by(:project_id => @project.identifier)
    if @master_password.nil?
      if User.current.admin?
        redirect_to new_project_master_path
      else
        flash[:error] = 'Master password not found!'
        flash[:notice] = 'Ask the administrator to set a master password!'
      end
    end
  end

  def new
    @vault = Vault.new()
  end

  def create

  end

  def update

  end

  def edit

  end

  def destroy

  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/vaults_controller.rb
require 'digest/md5'
require 'digest/sha2'
require 'openssl'
require 'base64'

class VaultsController < ApplicationController
  unloadable
  include VaultsHelper
  before_filter :find_project, :authorize

  helper :attachments
  include AttachmentsHelper

  def index
    #check that master password exist
    @master_password = MasterPassword.find_by(:project_id => @project)
    if @master_password.nil?
      # master password dose not exist
      if User.current.admin?
        flash[:notice] = 'Create new master password for encrypting vault!'
        redirect_to new_project_master_path
      else
        flash[:error] = 'Master password not found!'
        flash[:notice] = 'Ask the administrator to set a master password!'
      end
    else
      # master password exist
      @master = read_master_cache(User.current.id, @project.id)
      if @master.nil?
        # no master in cache
        redirect_to '/projects/' + @project.identifier + '/decrypt'
      else
        @vault_passwords = Vault.where(:project => @project).where(:private => false).all
        @vault_passwords_p = Vault.where(:project => @project).where(:user => User.current).where(:private => true).all
      end
    end
  end

  def new
    @master = read_master_cache(User.current.id, @project.id)
    if @master.nil?
      # no master in cache
      redirect_to '/projects/' + @project.identifier + '/decrypt'
    else
      @vault = Vault.new()
    end
  end

  def create
    @master = params[:vault][:master]
    # test cache
    master_from_cache = read_master_cache(User.current.id, @project.id)
    if master_from_cache.nil?
      flash[:error] = 'Session expired.'
      redirect_to ('/projects/' + @project.identifier + '/decrypt') and return
    end
    if master_from_cache != @master
      flash[:error] = 'Somebody change master password. Please enter new master password and try again create/update.'
      redirect_to ('/projects/' + @project.identifier + '/decrypt') and return
    end
    # end test cache
    form_params = vault_params
    # encrypt login and password
    form_params[:login] = vault_encrypt(form_params[:login], @master)
    form_params[:password] = vault_encrypt(form_params[:password], @master)
    @vault = Vault.new(form_params)
    @vault.project = @project
    @vault.user = User.current
    # refresh cache
    write_master_cache(User.current.id, @master, @project.id)
    if @vault.save
      # save successfully
      flash[:notice] = 'Password successfully added to vault.'
      # save attachment
      params[:attachments].each do |attachment_param|
        if attachment_param.length > 0
          if attachment_param[1].has_key?(:token)
            tokens = attachment_param[1][:token].split('.')
            attachment = Attachment.find(tokens[0].to_i)
          end
        end
        unless attachment.nil?
          attachment.container_type = Vault.name
          attachment.container_id = @vault.id
          attachment.save
        end
      end
      # end save attachment
      redirect_to(project_vaults_path) and return
    else
      # validation fail
      @vault.login = vault_decrypt(@vault.login, @master)
      @vault.password = vault_decrypt(@vault.password, @master)
      render :new
    end
  end

  def update
    @vault = Vault.find(params[:id])
    @master = params[:vault][:master]
    # test cache
    master_from_cache = read_master_cache(User.current.id, @project.id)
    if master_from_cache.nil?
      flash[:error] = 'Session expired.'
      redirect_to ('/projects/' + @project.identifier + '/decrypt') and return
    end
    if master_from_cache != @master
      flash[:error] = 'Somebody change master password. Please enter new master password and try again create/update.'
      redirect_to('/projects/' + @project.identifier + '/decrypt') and return
    end
    # end test cache
    form_params = vault_params
    form_params[:login] = vault_encrypt(form_params[:login], @master)
    form_params[:password] = vault_encrypt(form_params[:password], @master)
    @vault.assign_attributes(form_params)
    # refresh cache
    write_master_cache(User.current.id, @master, @project.id)
    if @vault.valid? and (request.patch? and @vault.save)
      # save successfully
      flash[:notice] = 'Password successfully added to vault.'
      flash[:notice] = 'Password successfully updated.'
      # save attachment
      params[:attachments].each do |attachment_param|
        if attachment_param.length > 0
          if attachment_param[1].has_key?(:token)
            tokens = attachment_param[1][:token].split('.')
            attachment = Attachment.find(tokens[0].to_i)
          end
        end
        unless attachment.nil?
          attachment.container_type = Vault.name
          attachment.container_id = @vault.id
          attachment.save
        end
      end
      # end save attachment
      redirect_to(project_vaults_path) and return
    else
      # validation fail
      @vault.login = vault_decrypt(@vault.login, @master)
      @vault.password = vault_decrypt(@vault.password, @master)
      render :edit
    end
  end

  def edit
    @master = read_master_cache(User.current.id, @project.id)
    if @master.nil?
      # no master in cache
      redirect_to '/projects/' + @project.identifier + '/decrypt'
    else
      @vault = Vault.find(params[:id])
      @vault.login = vault_decrypt(@vault.login, @master)
      @vault.password = vault_decrypt(@vault.password, @master)
    end
  end

  def destroy
    @master = read_master_cache(User.current.id, @project.id)
    if @master.nil?
      # no master in cache
      redirect_to '/projects/' + @project.identifier + '/decrypt'
    else
      @vault = Vault.find(params[:id])
      #@vault.delete
      @vault.destroy
      # refresh cache
      write_master_cache(User.current.id, @master, @project.id)
      redirect_to project_vaults_path
    end
  end

  def vault_params
    params.require(:vault).permit(:host, :login, :password, :notes, :private)
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def close_vault
    del_master_cache(User.current.id, @project.id)
    redirect_to '/projects/' + @project.identifier + '/decrypt'
  end
end

app/helpers/vaults_helper.rb
require 'digest/sha2'
require 'openssl'
require 'base64'

module VaultsHelper
  def vault_decrypt(value, cipher_key)
    if value.to_s != ''
      cipher = OpenSSL::Cipher.new('aes-256-cbc')
      cipher.decrypt
      cipher.key = Digest::SHA2.digest cipher_key
      cipher.update(Base64.decode64(value.to_s)) + cipher.final
    end
  end

  def vault_encrypt(value, cipher_key)
    if value.to_s != ''
      cipher = OpenSSL::Cipher.new('aes-256-cbc')
      cipher.encrypt
      cipher.key = Digest::SHA2.digest cipher_key
      Base64.encode64(cipher.update(value.to_s) + cipher.final)
    end
  end

  def write_master_cache(id, value, prj)
    # refresh cache
    expires_in = Setting.plugin_password_vault['VAULT_IDLE']
    m = expires_in.to_i
    Rails.cache.write(:"master#{id}#{prj}", value, expires_in: m.minute)
  end

  def read_master_cache(id, prj)
    Rails.cache.read(:"master#{id}#{prj}")
  end

  def del_master_cache(id, prj)
    Rails.cache.delete(:"master#{id}#{prj}")
  end

  def reset_master_cache(prj)
    users = User.status('1').all
    users.each do |u|
      Rails.cache.delete(:"master#{u.id}#{prj}")
    end
  end

  def item_output(type, value, notes)
    if type == 'RDP'
      url = '<a href="rdp://' + value + '">rdp://' + value + '</a>'
      return url.html_safe
    elsif type == 'HTTP'
      url = '<a href="http://' + value +'">' + value +'</a>'
      return url.html_safe
    elsif type == 'HTTPS'
      url = '<a href="https://' + value +'">' + value +'</a>'
      return url.html_safe
    else
      return value
    end
  end
end

app/views/vaults/_form.html.erb
<%= error_messages_for @vault %>

<div class="box tabular">
  <p><%= f.text_field :host, :require => false, :value => "#{@vault.host || ''}" %></p>

  <p><%= f.text_field :login, :require => true, :value => "#{@vault.login || ''}" %></p>

  <p><%= f.text_field :password, :require => true, :value => "#{@vault.password || ''}" %></p>

  <p><%= f.check_box :private, :require => false, :value => "#{@vault.private || 0}" %></p>

  <p><%= f.text_area :notes, :required => false, :cols => 40, :value => "#{@vault.notes || ''}", :rows => 15, :class => 'wiki-edit' %></p>

  <p><%= f.hidden_field :master, :required => true, :value => "#{@master}" %></p>

  <p><%= render :partial => 'attachments/form' %></p>
</div>

app/views/vaults/_nav.html.erb
<div class="contextual">
  <%= link_to('Add new password', new_project_vault_path(), :class => 'icon icon-add') %> |
  <%= link_to('Close vault', '/projects/' + @project.identifier + '/close-vault', :class => 'icon icon-lock') %>
</div>

app/views/vaults/edit.html.erb
<%= render :partial => "nav" %>

<h2>Edit password</h2>

<%= labelled_form_for @vault, :url => project_vaults_path + '/' + @vault.id.to_s, :html => {:id => 'vault-form'} do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <%= submit_tag 'Update' %>
<% end %>

app/views/vaults/index.html.erb
<% if @master_password %>
    <%= render :partial => 'nav' %>
    <h2>Passwords vault</h2>
    <div class="autoscroll">
      <table class="list vault">
        <thead>
        <tr>
          <th width="15%">Host</th>
          <th width="10%">Login</th>
          <th width="10%">Password</th>
          <th width="30%">Items</th>
          <th width="20%">Created by</th>
          <th width="20%">Notes</th>
          <th width="5%">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @vault_passwords.each do |password| %>
            <tr>
              <!--hostname-->
              <td class="a-left"><%= password.host %></td>
              <!--login-->
              <td>
                <%= vault_decrypt(password.login, @master) %>
                <a href="#" title="copy" class="icon icon-copy password-copy" data-clipboard-text="<%= vault_decrypt(password.login, @master) %>"></a>
              </td>
              <!--password-->
              <td>
                <span class="vault-password">
                  <%= vault_decrypt(password.password, @master) %>
                </span>
                <a href="#" title="copy" class="icon icon-copy password-copy" data-clipboard-text="<%= vault_decrypt(password.password, @master) %>"></a><a href="#" title="show/hide" class="icon icon-unlock password-lock"></a>
              </td>
              <!--items-->
              <td>
                <table class="items">
                  <% password.sitems.each do |item| %>
                      <tr>
                        <td width="70%">
                          <span class="sitem <%= item.sitem_type %>-sitem">
                            <%= item_output(item.sitem_type, item.sitem, item.notes) %>
                          </span>
                        </td>
                        <td width="30%">
                          <span class="sitem-actions">
                            <%= link_to '', edit_project_vault_sitem_path(:vault_id => password.id, :id => item.id), :class => 'icon icon-edit' %>
                            <%= link_to '', {:controller => 'sitems', :action => 'destroy', :vault_id => password.id, :id => item.id}, :method => :delete, :class => 'icon icon-del', data: {confirm: 'Delete item?'} %>
                          </span>
                        </td>
                      </tr>
                  <% end %>
                </table>
                <span class="add-sitem">
                  <%= link_to '', new_project_vault_sitem_path(:vault_id => password.id), :class => 'icon icon-add' %>
                </span>

                <% if password.attachments.length > 0 %>
                    <p><b>Attachments</b></p>
                    <p>
                      <%= render :partial => 'attachments/links', :locals => {
                          :attachments => password.attachments,
                          :options => {:editable => false, :deletable => true}
                      } %>
                    </p>
                <% end %>
              </td>
              <!--owner-->
              <td><%= password.user %></td>
              <!--notes-->
              <td><%= password.notes %></td>
              <td>
                <%= link_to '', {:action => 'edit', :id => password.id}, :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
                <%= link_to '', {:action => 'destroy', :id => password.id}, :method => :delete, :class => 'icon icon-del', data: {confirm: 'Delete password?'} %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <!--private passwords-->
    <h2>Private passwords vault</h2>
    <div class="autoscroll">
      <table class="list vault">
        <thead>
        <tr>
          <th width="15%">Host</th>
          <th width="10%">Login</th>
          <th width="10%">Password</th>
          <th width="30%">Items</th>
          <th width="20%">Created by</th>
          <th width="20%">Notes</th>
          <th width="5%">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @vault_passwords_p.each do |password| %>
            <tr>
              <!--host-->
              <td class="a-left"><%= password.host %></td>
              <!--login-->
              <td>
                <%= vault_decrypt(password.login, @master) %>
                <a href="#" title="copy" class="icon icon-copy password-copy" data-clipboard-text="<%= vault_decrypt(password.login, @master) %>"></a>
              </td>
              <!--password-->
              <td>
                <span class="vault-password">
                  <%= vault_decrypt(password.password, @master) %>
                </span>
                <a href="#" title="copy" class="icon icon-copy password-copy" data-clipboard-text="<%= vault_decrypt(password.password, @master) %>"></a><a href="#" title="show/hide" class="icon icon-unlock password-lock"></a>
              </td>
              <!--items-->
              <td>
                <table class="items">
                  <% password.sitems.each do |item| %>
                      <tr>
                        <td width="70%">
                          <span class="sitem <%= item.sitem_type %>-sitem">
                            <%= item_output(item.sitem_type, item.sitem, item.notes) %>
                          </span>
                        </td>
                        <td width="30%">
                          <span class="sitem-actions">
                            <%= link_to '', edit_project_vault_sitem_path(:vault_id => password.id, :id => item.id), :class => 'icon icon-edit' %>
                            <%= link_to '', {:controller => 'sitems', :action => 'destroy', :vault_id => password.id, :id => item.id}, :method => :delete, :class => 'icon icon-del', data: {confirm: 'Delete item?'} %>
                          </span>
                        </td>
                      </tr>
                  <% end %>
                </table>
                <span class="add-sitem">
                  <%= link_to '', new_project_vault_sitem_path(:vault_id => password.id), :class => 'icon icon-add' %>
                </span>

                <% if password.attachments.length > 0 %>
                    <p><b>Attachments</b></p>
                    <p>
                      <%= render :partial => 'attachments/links', :locals => {
                          :attachments => password.attachments,
                          :options => {:editable => false, :deletable => true}
                      } %>
                    </p>
                <% end %>
              </td>
              <!--owner-->
              <td><%= password.user %></td>
              <!--notes-->
              <td><%= password.notes %></td>
              <!--actions-->
              <td>
                <%= link_to '', {:action => 'edit', :id => password.id}, :class => 'icon icon-edit', :accesskey => accesskey(:edit) %>
                <%= link_to '', {:action => 'destroy', :id => password.id}, :method => :delete, :class => 'icon icon-del', data: {confirm: 'Delete password?'} %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% if User.current.admin? %>
        <div class="contextual">
          <%= link_to('Change master password', {:action => 'change_master', :controller => 'masters'}, :class => 'icon icon-passwd') %>
        </div>
    <% end %>
<% end %>
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'vaults', :plugin => 'password_vault' %>
    <%= javascript_include_tag 'clipboard.min', :plugin => 'password_vault' %>
    <%= javascript_include_tag 'vaults', :plugin => 'password_vault' %>
<% end %>
<script type="text/javascript">
  setTimeout(function () {
    location = ''
  }, 60000)
</script>

app/views/vaults/new.html.erb
<%= render :partial => "nav" %>

<h2>Add new password</h2>

<%= labelled_form_for @vault, :url => project_vaults_path, :html => {:id => 'vault-form'} do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <%= submit_tag 'Create' %>
<% end %>

app/views/vaults/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>