config/routes.rb
resources :projects do
  resources :vaults
end

resources :projects do
  resources :masters
end

resources :projects do
  resources :vaults do
    resources :sitems
  end
end

get 'projects/:project_id/decrypt', :to => 'masters#decrypt'
post 'projects/:project_id/decrypt', :to=> 'masters#decrypt_post'
get 'projects/:project_id/change-master', :to => 'masters#change_master'
post 'projects/:project_id/change-master', :to => 'masters#change_master_post'
get 'projects/:project_id/close-vault', :to => 'vaults#close_vault'

app/controllers/masters_controller.rb
require 'digest/md5'
class MastersController < ApplicationController
  unloadable
  include VaultsHelper
  before_filter :find_project, :authorize

  # form for new master password for project vault
  def new
    @master_password = MasterPassword.new
  end

  # create new master password for project vault
  def create
    passwords = params[:master_password]
    logger.info(passwords)
    if (passwords[:password] == passwords[:password_repeat] and passwords[:password] != '')
      digest = Digest::MD5.hexdigest(master_params[:password])
      logger.info(digest)
      @master_password = MasterPassword.new(:password => digest)
      @master_password.project = @project
      @master_password.save()
      flash[:notice] = 'Master password created.'
      redirect_to project_vaults_path
    else
      flash[:error] = 'Password mismatch.'
      @master_password = MasterPassword.new
      render :new
    end
  end

  # form for enter master password for decrypt vault
  def decrypt
    @master_password = MasterPassword.new
  end

  # check master password
  def decrypt_post
    password = master_params[:password]
    digest = Digest::MD5.hexdigest(password)
    master_digest = MasterPassword.find_by(:project_id => @project)
    if digest == master_digest.password
      write_master_cache(User.current.id, password, @project.id)
      redirect_to project_vaults_path
    else
      flash[:error] = 'Wrong master password!'
      redirect_to '/projects/' + @project.identifier + '/decrypt'
    end
  end

  # form for change  master password
  def change_master
    unless User.current.admin?
      redirect_to(project_vaults_path) and return
    end
    @master = read_master_cache(User.current.id, @project.id)
    if @master.nil?
      # no master in cache
      redirect_to('/projects/' + @project.identifier + '/decrypt')and return
    else
      @change_password = MasterPassword.new
    end
  end

  # decrypt/encrypt change master password
  def change_master_post
    passwords = params[:master_password]
    old_password = passwords[:old_password]
    old_password_digest1 = Digest::MD5.hexdigest(old_password)
    old_password_digest2 = MasterPassword.find_by(:project_id => @project)
    if (old_password_digest1 == old_password_digest2.password and passwords[:new_password] == passwords[:password_repeat] and passwords[:new_password] != '')
      # decrypt-encrypt all passwords
      @vault_passwords = Vault.where(:project => @project).all
      @vault_passwords.each do |p|
        login = vault_decrypt(p.login, old_password)
        password = vault_decrypt(p.password, old_password)
        login = vault_encrypt(login, passwords[:new_password])
        password = vault_encrypt(password, passwords[:new_password])
        p.update(login: login, password: password)
      end
      # save new password digest
      digest = Digest::MD5.hexdigest(passwords[:new_password])
      old_password_digest2.update(password: digest)
      # refresh cache
      reset_master_cache(@project.id)
      write_master_cache(User.current.id, passwords[:new_password], @project.id)
      # notice
      flash[:notice] = 'Master password changed. Do not forget announce a new password to your employees.'
      redirect_to project_vaults_path
    else
      flash[:error] = 'Password mismatch.'
      redirect_to project_vaults_path
    end
  end

  # get params for creating new master password
  def master_params
    params.require(:master_password).permit(:password)
  end

  # find project id
  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/masters/change_master.html.erb
<%= labelled_form_for @change_password, :url => '/projects/' + @project.identifier + '/change-master', :html => {:id => 'change-master-form'} do |f| %>
    <%= error_messages_for @change_password %>
    <div class="box tabular">
      <p><%= f.password_field :old_password, :require => true, :value => '' %></p>
      <p><%= f.password_field :new_password, :require => true, :value => '' %></p>
      <p><%= f.password_field :password_repeat, :require => true, :value => '' %></p>
    </div>
    <%= submit_tag 'Change' %>
<% end %>

app/views/masters/decrypt.html.erb
<%= labelled_form_for @master_password, :url => '/projects/' + @project.identifier + '/decrypt', :html => {:id => 'master-form'} do |f| %>
    <%= error_messages_for @master_password %>
    <div class="box tabular">
      <p><%= f.password_field :password, :require => true, :value => '' %></p>
    </div>
    <%= submit_tag 'Decrypt' %>
<% end %>

app/views/masters/new.html.erb
<%= labelled_form_for @master_password, :url => project_masters_path, :html => {:id => 'master-form'} do |f| %>
    <%= error_messages_for @master_password %>
    <div class="box tabular">
      <p><%= f.password_field :password, :require => true, :value => '' %></p>
      <p><%= f.password_field :password_repeat, :require => true, :value => '' %></p>
    </div>
    <%= submit_tag 'Create' %>
<% end %>