config/routes.rb
resources :projects do
  resources :vaults
end

resources :projects do
  resources :masters
end

resources :projects do
  resources :vaults do
    resources :sitems
  end
end

get 'projects/:project_id/decrypt', :to => 'masters#decrypt'
post 'projects/:project_id/decrypt', :to=> 'masters#decrypt_post'
get 'projects/:project_id/change-master', :to => 'masters#change_master'
post 'projects/:project_id/change-master', :to => 'masters#change_master_post'
get 'projects/:project_id/close-vault', :to => 'vaults#close_vault'

app/models/sitem.rb
class Sitem < ActiveRecord::Base
  unloadable
  belongs_to :vault, :class_name => "Vault", :foreign_key => "vault_id"
  attr_accessible :sitem_type, :sitem, :notes
  validates_presence_of :sitem_type, :sitem
end

app/controllers/sitems_controller.rb
class SitemsController < ApplicationController
  unloadable
  include VaultsHelper
  before_filter :find_project, :authorize

  def new
    @vault_id = params[:vault_id]
    @sitem = Sitem.new
  end

  def create
    @vault_id = params[:vault_id]
    @sitem = Sitem.new(sitem_params)
    @sitem.vault_id = @vault_id
    if @sitem.save
      flash[:notice] = 'Item successfully added.'
      redirect_to(project_vaults_path) and return
    else
      render :new
    end
  end

  def edit
    @vault_id = params[:vault_id]
    @sitem = Sitem.find(params[:id])
  end

  def update
    @sitem = Sitem.find(params[:id])
    @sitem.assign_attributes(sitem_params)
    if @sitem.valid? and (request.patch? and @sitem.save)
      # save successfully
      flash[:notice] = 'Item successfully updated.'
      redirect_to(project_vaults_path) and return
    else
      # validation fail
      render :edit
    end
  end

  def destroy
    @master = read_master_cache(User.current.id, @project.id)
    if @master.nil?
      # no master in cache
      redirect_to '/projects/' + @project.identifier + '/decrypt'
    else
      @sitem = Sitem.find(params[:id])
      @sitem.delete
      # refresh cache
      write_master_cache(User.current.id, @master, @project.id)
      redirect_to project_vaults_path
    end
  end

  def sitem_params
    params.require(:sitem).permit(:sitem_type, :sitem, :notes)
  end

  def find_project
    @project = Project.find(params[:project_id])
  end
end

app/helpers/sitems_helper.rb
module SitemsHelper
end

app/views/sitems/_form.html.erb
<%= error_messages_for @sitem %>

<div class="box tabular">
  <p><%= f.select :sitem_type, ['RDP', 'HTTP', 'HTTPS', 'TeamViewer', 'Other'] %></p>

  <p><%= f.text_field :sitem, :require => true, :value => "#{@sitem.sitem || ''}" %></p>

  <p><%= f.text_area :notes, :required => false, :value => "#{@sitem.notes || ''}", :class => 'wiki-edit' %></p>
</div>

app/views/sitems/edit.html.erb
<h2>Edit item</h2>

<%= labelled_form_for @sitem, :url => project_vaults_path + '/' + @vault_id.to_s + '/sitems/' + @sitem.id.to_s, :html => {:id => 'sitem-form'} do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <%= submit_tag 'Update' %>
<% end %>

app/views/sitems/new.html.erb
<h2>Add new item</h2>

<%= labelled_form_for @sitem, :url => project_vault_sitems_path(:vault_id => @vault_id), :html => {:id => 'sitem-form'} do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>
    <%= submit_tag 'Create' %>
<% end %>